CREATE TABLE `QUANTRIVIEN` (
  `MAQTV` int PRIMARY KEY AUTO_INCREMENT,
  `TENTK` VARCHAR(50),
  `MATKHAU` VARCHAR(32)
);

CREATE TABLE `NGUOIDUNG` (
  `MATK` INT PRIMARY KEY AUTO_INCREMENT,
  `TENTK` VARCHAR(30) UNIQUE,
  `HOTEN` VARCHAR(50),
  `EMAIL` VARCHAR(150) UNIQUE,
  `SDT` varchar(10) UNIQUE,
  `MATKHAU` varchar(32),
  `NGLAPTK` DATE,
  `DCHI` varchar(200),
  `TRANGTHAI` bit(1)
);

CREATE TABLE `HANGSANXUAT` (
  `MAHSX` int PRIMARY KEY AUTO_INCREMENT,
  `TENHSX` varchar(30),
  `LOGO` BLOB
);

CREATE TABLE `SANPHAM` (
  `MASP` int PRIMARY KEY AUTO_INCREMENT,
  `TENSP` varchar(150),
  `GIA` float,
  `KHUYENMAI` int,
  `MOTA` text,
  `SOSAO` int,
  `NGSX` date,
  `MAHSX` int,
  `TRANGTHAI` bit(1)
);

CREATE TABLE `KICHCO` (
  `MASP` int,
  `MAKC` int AUTO_INCREMENT,
  `COGIAY` float,
  `SOLUONG` int,
  PRIMARY KEY(`MAKC`, `MASP`)
);

CREATE TABLE `HINHANH` (
  `MASP` int,
  `MAHA` int,
  `FILE` BLOB,
  PRIMARY KEY (`MAHA`, `MASP`)
);

CREATE TABLE `HOADON` (
  `MAHD` int PRIMARY KEY AUTO_INCREMENT,
  `MATK` INT,
  `TONGTIEN` float,
  `HOTENKH` varchar(50),
  `EMAIL` varchar(150),
  `SDT` varchar(15),
  `DCHI` varchar(200),
  `GHICHU` text,
  `NGLAPHD` date,
  `MATT` INT
);

CREATE TABLE `TRANGTHAI` (
  `MATT` INT PRIMARY KEY AUTO_INCREMENT,
  `TENTT` varchar(255)
);

CREATE TABLE `CHITIETHOADON` (
  `MASP` int,
  `MAHD` int,
  `MAKC` int,
  `SOLUONG` int,
  `GIA` float,
  PRIMARY KEY (`MAHD`, `MASP`, `MAKC`)
);

CREATE TABLE `DANHMUC` (
  `MADM` INT PRIMARY KEY AUTO_INCREMENT,
  `TENDM` varchar(255)
);

CREATE TABLE `PHANLOAI` (
  `MADM` INT,
  `MASP` INT,
  PRIMARY KEY (`MADM`, `MASP`)
);

CREATE TABLE `GIOHANG` (
  `MAGH` INT PRIMARY KEY AUTO_INCREMENT,
  `MATK` INT
);

CREATE TABLE `CHITIETGIOHANG` (
  `MAGH` INT,
  `MASP` INT,
  `MAKC` int,
  `SOLUONG` INT,
  `GIA` float,
  PRIMARY KEY (`MAGH`, `MASP`, `MAKC`)
);

ALTER TABLE `SANPHAM` ADD FOREIGN KEY (`MAHSX`) REFERENCES `HANGSANXUAT` (`MAHSX`);

ALTER TABLE `HINHANH` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `KICHCO` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETHOADON` ADD FOREIGN KEY (`MAHD`) REFERENCES `HOADON` (`MAHD`);

ALTER TABLE `CHITIETHOADON` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETHOADON` ADD FOREIGN KEY (`MAKC`) REFERENCES `KICHCO` (`MAKC`);

ALTER TABLE `HOADON` ADD FOREIGN KEY (`MATK`) REFERENCES `NGUOIDUNG` (`MATK`);

ALTER TABLE `PHANLOAI` ADD FOREIGN KEY (`MADM`) REFERENCES `DANHMUC` (`MADM`);

ALTER TABLE `PHANLOAI` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETGIOHANG` ADD FOREIGN KEY (`MAGH`) REFERENCES `GIOHANG` (`MAGH`);

ALTER TABLE `CHITIETGIOHANG` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETGIOHANG` ADD FOREIGN KEY (`MAKC`) REFERENCES `KICHCO` (`MAKC`);

ALTER TABLE `GIOHANG` ADD FOREIGN KEY (`MATK`) REFERENCES `NGUOIDUNG` (`MATK`);

ALTER TABLE `HOADON` ADD FOREIGN KEY (`MATT`) REFERENCES `TRANGTHAI` (`MATT`);

INSERT INTO `nguoidung` (`MATK`, `TENTK`, `HOTEN`, `EMAIL`, `SDT`, `MATKHAU`, `NGLAPTK`, `DCHI`, `TRANGTHAI`) VALUES
(1, 'mkhoa', 'Trần Hoàng Minh Khoa', '0306231298@caothang.edu.vn', '0306231298', 'a4a6f167cfba8b8c4ba43436619ebafd', '2024-11-23', '159 Nam Kỳ Khởi Nghĩa, Phường Võ Thị Sáu, Quận 3, Hồ Chí Minh', b'1'),
(2, 'khuy', 'Huỳnh Khắc Huy', '0306231291@caothang.edu.vn', '0306231291', '0c9300550669a652d36c86dadfb9b843', '2024-11-13', '65 Đ. Huỳnh Thúc Kháng, Bến Nghé, Quận 1, Hồ Chí Minh', b'1');

INSERT INTO `quantrivien` (`MAQTV`, `TENTK`, `MATKHAU`) VALUES
(1, 'admin', '21232f297a57a5a743894a0e4a801fc3'),
(2, 'mkhoa', 'a4a6f167cfba8b8c4ba43436619ebafd'),
(3, 'khuy', '0c9300550669a652d36c86dadfb9b843');

INSERT INTO `trangthai` (`MATT`, `TENTT`) VALUES
(1, 'Chờ xác nhận'),
(2, 'Đã xác nhận'),
(3, 'Đang giao'),
(4, 'Đã giao'),
(10, 'Đã hủy');