CREATE TABLE `QUANTRIVIEN` (
  `MAQTV` int PRIMARY KEY AUTO_INCREMENT,
  `TENTK` VARCHAR(50),
  `MATKHAU` VARCHAR(32)
);

CREATE TABLE `NGUOIDUNG` (
  `MATK` INT PRIMARY KEY AUTO_INCREMENT,
  `TENTK` VARCHAR(30) UNIQUE,
  `HOTEN` VARCHAR(50),
  `EMAIL` VARCHAR(150) UNIQUE,
  `SDT` varchar(10) UNIQUE,
  `MATKHAU` varchar(32),
  `NGLAPTK` DATE,
  `TRANGTHAI` bit(1)
);

CREATE TABLE `HANGSANXUAT` (
  `MAHSX` int PRIMARY KEY AUTO_INCREMENT,
  `TENHSX` varchar(30),
  `LOGO` BLOB
);

CREATE TABLE `SANPHAM` (
  `MASP` int PRIMARY KEY AUTO_INCREMENT,
  `TENSP` varchar(150),
  `GIA` float,
  `KHUYENMAI` int,
  `MOTA` text,
  `SOSAO` int,
  `NGLAPSP` date,
  `MAHSX` int,
  `TRANGTHAI` bit(1)
);

CREATE TABLE `KICHCO` (
  `MAKC` int PRIMARY KEY AUTO_INCREMENT,
  `MASP` int,
  `COGIAY` float,
  `SOLUONG` int
);

CREATE TABLE `HINHANH` (
  `MAHA` int,
  `MASP` int,
  `URL` BLOB,
  PRIMARY KEY (`MAHA`, `MASP`)
);

CREATE TABLE `HOADON` (
  `MAHD` int PRIMARY KEY AUTO_INCREMENT,
  `MATK` INT,
  `HOTENKH` varchar(50),
  `EMAIL` varchar(150),
  `SDT` varchar(15),
  `DCHI` varchar(200),
  `GHICHU` text,
  `NGLAPHD` date,
  `MATT` INT
);

CREATE TABLE `TRANGTHAI` (
  `MATT` INT PRIMARY KEY AUTO_INCREMENT,
  `TENTT` varchar(255)
);

CREATE TABLE `CHITIETHOADON` (
  `MAHD` int,
  `MASP` int,
  `MAKC` int,
  `SOLUONG` int,
  `GIA` float,
  PRIMARY KEY (`MAHD`, `MASP`, `MAKC`)
);

CREATE TABLE `DANHMUC` (
  `MADM` INT PRIMARY KEY AUTO_INCREMENT,
  `TENDM` varchar(255)
);

CREATE TABLE `PHANLOAI` (
  `MADM` INT,
  `MASP` INT,
  PRIMARY KEY (`MADM`, `MASP`)
);

CREATE TABLE `GIOHANG` (
  `MAGH` INT AUTO_INCREMENT,
  `MATK` INT,
  PRIMARY KEY (`MAGH`, `MATK`)
);

CREATE TABLE `CHITIETGIOHANG` (
  `MAGH` INT,
  `MASP` INT,
  `MAKC` int,
  `SOLUONG` INT,
  `GIA` float,
  PRIMARY KEY (`MAGH`, `MASP`, `MAKC`)
);

ALTER TABLE `SANPHAM` ADD FOREIGN KEY (`MAHSX`) REFERENCES `HANGSANXUAT` (`MAHSX`);

ALTER TABLE `HINHANH` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `KICHCO` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETHOADON` ADD FOREIGN KEY (`MAHD`) REFERENCES `HOADON` (`MAHD`);

ALTER TABLE `CHITIETHOADON` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETHOADON` ADD FOREIGN KEY (`MAKC`) REFERENCES `KICHCO` (`MAKC`);

ALTER TABLE `HOADON` ADD FOREIGN KEY (`MATK`) REFERENCES `NGUOIDUNG` (`MATK`);

ALTER TABLE `PHANLOAI` ADD FOREIGN KEY (`MADM`) REFERENCES `DANHMUC` (`MADM`);

ALTER TABLE `PHANLOAI` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETGIOHANG` ADD FOREIGN KEY (`MAGH`) REFERENCES `GIOHANG` (`MAGH`);

ALTER TABLE `CHITIETGIOHANG` ADD FOREIGN KEY (`MASP`) REFERENCES `SANPHAM` (`MASP`);

ALTER TABLE `CHITIETGIOHANG` ADD FOREIGN KEY (`MAKC`) REFERENCES `KICHCO` (`MAKC`);

ALTER TABLE `GIOHANG` ADD FOREIGN KEY (`MATK`) REFERENCES `NGUOIDUNG` (`MATK`);

ALTER TABLE `HOADON` ADD FOREIGN KEY (`MATT`) REFERENCES `TRANGTHAI` (`MATT`);
