<?php
  include_once("components/header.php");
  include_once("components/loginForm.php");
  include_once("components/landingPage.php");
  include_once("components/filterPanel.php");
  include_once("components/productCard.php");
  include_once("components/productList.php");
  include_once("components/footer.php");
?>